const entityMap = {
  '&lt;': '<',
  '&gt;': '>',
  '&amp;': '&',
  '&quot;': '"',
  '&#39;': "'",
  '&le;': '≤',
  '&ge;': '≥',
  '&ne;': '≠',
  '&times;': '×',
  '&divide;': '÷',
  '&plusmn;': '±',
  '&minus;': '−',
  '&infin;': '∞',
  '&pi;': 'π',
  '&alpha;': 'α',
  '&beta;': 'β',
  '&gamma;': 'γ',
  '&delta;': 'δ',
  '&theta;': 'θ',
  '&lambda;': 'λ',
  '&mu;': 'μ',
  '&sigma;': 'σ',
  '&tau;': 'τ',
  '&phi;': 'φ',
  '&omega;': 'ω',
  '&sum;': '∑',
  '&prod;': '∏',
  '&int;': '∫',
  '&radic;': '√',
  '&part;': '∂',
  '&nabla;': '∇',
  '&isin;': '∈',
  '&notin;': '∉',
  '&sub;': '⊂',
  '&sup;': '⊃',
  '&cup;': '∪',
  '&cap;': '∩',
  '&empty;': '∅',
  '&forall;': '∀',
  '&exist;': '∃',
  '&rarr;': '→',
  '&larr;': '←',
  '&harr;': '↔',
  '&rArr;': '⇒',
  '&lArr;': '⇐',
  '&hArr;': '⇔',
  '&prime;': '′',
  '&Prime;': '″',
  '&deg;': '°',
  '&perp;': '⊥',
  '&sdot;': '⋅',
  '&lceil;': '⌈',
  '&rceil;': '⌉',
  '&lfloor;': '⌊',
  '&rfloor;': '⌋',
  '&loz;': '◊',
  '&sim;': '∼',
  '&asymp;': '≈',
  '&equiv;': '≡',
  '&prop;': '∝',
  '&ang;': '∠',
  '&oplus;': '⊕',
  '&otimes;': '⊗',
};

export function decodeHtmlEntities(str) {
  return str.replace(/&[a-zA-Z0-9#]+;/g, (entity) => {
    if (entityMap[entity] !== undefined) return entityMap[entity];
    const decMatch = entity.match(/^&#(\d+);$/);
    if (decMatch) return String.fromCharCode(parseInt(decMatch[1], 10));
    const hexMatch = entity.match(/^&#x([0-9a-fA-F]+);$/);
    if (hexMatch) return String.fromCharCode(parseInt(hexMatch[1], 16));
    return entity;
  });
}
