import React from 'react';
import 'katex/dist/katex.min.css';
import { printStyles } from './StudyGuidePrintStyles';
import { sanitizeHTML } from '../../../utils/sanitizeHTML';
import Logo from '../../../assets/co_tutor_logo.png';

const StudyGuidePrintView = React.forwardRef(({ simulation, htmlContent, snapshotDataUrl }, ref) => {
  // Strip redundant leading <h1> tags matching the document title
  const cleanHtml = React.useMemo(() => {
    if (!htmlContent) return '';
    return htmlContent.replace(/^\s*<h1\b[^>]*>[\s\S]*?<\/h1>/i, '');
  }, [htmlContent]);

  return (
    <div
      ref={ref}
      className="print-container"
        style={{
          fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
          color: '#1e293b',
          backgroundColor: '#ffffff'
        }}
      >
        <style type="text/css">{printStyles}</style>

        {/* Academic Document Header */}
        <div style={{ borderBottom: '2px solid #0095b6', paddingBottom: '14px', marginBottom: '20px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '12px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <img src={Logo} alt="Co-Tutor" style={{ height: '28px', width: 'auto' }} />
              <div>
                <span style={{ fontSize: '15px', fontWeight: 800, color: '#0f172a', letterSpacing: '-0.02em' }}>Co-Tutor</span>
                <span style={{ fontSize: '10px', color: '#007695', fontWeight: 700, marginLeft: '6px', textTransform: 'uppercase' }}>Interactive Study Guide</span>
              </div>
            </div>
            <div style={{ backgroundColor: '#e0f8fc', color: '#007695', padding: '4px 10px', borderRadius: '20px', fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
              {simulation?.subject || 'Science'}
            </div>
          </div>

          <h1 style={{ margin: '0 0 6px 0', color: '#0f172a', fontSize: '24px', fontWeight: 800, fontFamily: "'Outfit', sans-serif", lineHeight: 1.2 }}>
            {simulation?.topic}
          </h1>
          <p style={{ margin: 0, color: '#64748b', fontSize: '11px', fontWeight: 500 }}>
            Generated on {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>

          {snapshotDataUrl && (
            <div style={{ marginTop: '14px', textAlign: 'center' }}>
              <img
                src={snapshotDataUrl}
                alt="Simulation Visual Snapshot"
                style={{ maxHeight: '200px', maxWidth: '100%', borderRadius: '8px', border: '1px solid #e2e8f0', objectFit: 'contain' }}
              />
            </div>
          )}
        </div>

        {/* AI Content with Pre-processed KaTeX and Styled Tables */}
        {cleanHtml && (
          <div
            className="pdf-content"
            dangerouslySetInnerHTML={{ __html: sanitizeHTML(cleanHtml) }}
          />
        )}

        {/* Footer */}
        <div style={{ marginTop: '30px', borderTop: '1px solid #e2e8f0', paddingTop: '12px', textAlign: 'center', breakInside: 'avoid', pageBreakInside: 'avoid' }}>
          <p style={{ color: '#94a3b8', fontSize: '10px', fontWeight: 500, margin: 0 }}>
            Generated by Co-Tutor • Interactive STEM Learning Platform
          </p>
        </div>
    </div>
  );
});

export default StudyGuidePrintView;
