/**
 * Transforms standard HTML into Word-compatible HTML format,
 * ensuring tables, headers, lists, code, and callouts render with exact page fitting in MS Word.
 */
export function formatHtmlForWord(rawHtml) {
  if (!rawHtml) return '';

  let html = rawHtml;

  // 1. Strip redundant leading <h1> matching the document title
  html = html.replace(/^\s*<h1\b[^>]*>[\s\S]*?<\/h1>/i, '');

  // 2. Add explicit Word table styling, borders, and cell padding (preventing splitting)
  html = html.replace(/<table\b[^>]*>/gi, '<table border="1" cellpadding="6" cellspacing="0" style="border-collapse: collapse; width: 100%; border: 1pt solid #94a3b8; margin: 8pt 0; page-break-inside: avoid !important; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-family: Calibri, Arial, sans-serif;">');
  html = html.replace(/<tr\b[^>]*>/gi, '<tr style="page-break-inside: avoid !important;">');
  html = html.replace(/<th\b[^>]*>/gi, '<th style="background-color: #007695; color: #ffffff; font-weight: bold; border: 1pt solid #005e77; padding: 6pt 8pt; text-align: left; font-family: Calibri, Arial, sans-serif; font-size: 9.5pt;">');
  html = html.replace(/<td\b[^>]*>/gi, '<td style="border: 1pt solid #cbd5e1; padding: 5pt 8pt; font-family: Calibri, Arial, sans-serif; font-size: 9pt; color: #1e293b; vertical-align: middle;">');

  // 3. Blockquotes and Code
  html = html.replace(/<blockquote\b[^>]*>/gi, '<blockquote style="border-left: 2.5pt solid #0095b6; background-color: #f0fdfa; padding: 6pt 10pt; margin: 8pt 0; font-style: italic; color: #0f766e; page-break-inside: avoid !important;">');
  html = html.replace(/<pre\b[^>]*>/gi, '<pre style="background-color: #f8fafc; border: 1pt solid #cbd5e1; padding: 6pt 8pt; font-family: Consolas, \'Courier New\', monospace; font-size: 9pt; color: #0f172a; margin: 8pt 0; page-break-inside: avoid !important;">');

  // 4. Ensure spacing around math tags to avoid glued words
  html = html.replace(/(<\/math>)([a-zA-Z0-9(])/g, '$1 $2');
  html = html.replace(/([a-zA-Z0-9)])(<math)/g, '$1 $2');

  return html;
}

export function buildWordDocumentHtml(title, subject, bodyContent) {
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  return `<!DOCTYPE html>
<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
<head>
  <meta charset='utf-8'>
  <title>${title} - Study Guide</title>
  <!--[if gte mso 9]>
  <xml>
    <w:WordDocument>
      <w:View>Print</w:View>
      <w:Zoom>100</w:Zoom>
      <w:DoNotOptimizeForBrowser/>
    </w:WordDocument>
  </xml>
  <![endif]-->
  <style>
    @page Section1 { size: 595.3pt 841.9pt; margin: 42.5pt 51.0pt 42.5pt 51.0pt; mso-header-margin: 36pt; mso-footer-margin: 36pt; mso-paper-source: 0; }
    div.Section1 { page: Section1; }
    body { font-family: Calibri, 'Segoe UI', Arial, sans-serif; font-size: 10pt; line-height: 1.45; color: #1e293b; margin: 0; }
    h1 { font-family: 'Segoe UI', Arial, sans-serif; color: #0f172a; font-size: 18pt; margin-top: 2pt; margin-bottom: 2pt; page-break-after: avoid !important; }
    h2 { font-family: 'Segoe UI', Arial, sans-serif; color: #007695; font-size: 13pt; margin-top: 12pt; margin-bottom: 4pt; border-bottom: 1.5pt solid #e0f8fc; padding-bottom: 2pt; page-break-after: avoid !important; }
    h3 { font-family: 'Segoe UI', Arial, sans-serif; color: #0f172a; font-size: 11pt; margin-top: 10pt; margin-bottom: 3pt; page-break-after: avoid !important; }
    p { margin-top: 3pt; margin-bottom: 4pt; color: #334155; line-height: 1.45; }
    ul, ol { margin-top: 2pt; margin-bottom: 4pt; padding-left: 18pt; }
    li { margin-bottom: 2pt; color: #334155; line-height: 1.45; }
    table { border-collapse: collapse; width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; margin: 8pt 0; page-break-inside: avoid !important; }
    tr { page-break-inside: avoid !important; }
    th { background-color: #007695; color: #ffffff; font-weight: bold; border: 1pt solid #005e77; padding: 6pt 8pt; font-size: 9.5pt; text-align: left; }
    td { border: 1pt solid #cbd5e1; padding: 5pt 8pt; font-size: 9pt; color: #1e293b; }
    .badge { background-color: #e0f8fc; color: #007695; font-weight: bold; font-size: 9pt; padding: 2.5pt 7pt; border-radius: 3pt; display: inline-block; text-transform: uppercase; }
  </style>
</head>
<body>
<div class="Section1">
  <p class="badge">${subject ? subject.toUpperCase() : 'CO-TUTOR'} • INTERACTIVE STUDY GUIDE</p>
  <h1>${title}</h1>
  <p style="color: #64748b; font-size: 9pt; margin-top: 2pt; margin-bottom: 8pt;">Generated by Co-Tutor on ${dateStr}</p>
  <hr style="border: none; border-top: 1.5pt solid #0095b6; margin: 0 0 12pt 0;" />
  ${bodyContent}
  <hr style="border: none; border-top: 1pt solid #e2e8f0; margin: 16pt 0 6pt 0;" />
  <p style="text-align: center; color: #94a3b8; font-size: 8.5pt;">Generated by Co-Tutor • Interactive STEM Learning Platform</p>
</div>
</body>
</html>`;
}
